steps:
  # 1. Builda a imagem Docker
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t', 'gcr.io/$PROJECT_ID/dev-notafiscalsimples-com',
        '--build-arg', 'NEXT_PUBLIC_SUPABASE_URL=${_NEXT_PUBLIC_SUPABASE_URL}',
        '--build-arg', 'NEXT_PUBLIC_SUPABASE_ANON_KEY=${_NEXT_PUBLIC_SUPABASE_ANON_KEY}',
        '.'
      ]

  # 2. Faz push da imagem para o Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      [
        'push',
        'gcr.io/$PROJECT_ID/dev-notafiscalsimples-com'
      ]

  # 3. Faz deploy no Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      [
        'run', 'deploy', 'dev-notafiscalsimples-com',
        '--image', 'gcr.io/$PROJECT_ID/dev-notafiscalsimples-com',
        '--region', 'us-central1',
        '--platform', 'managed',
        '--allow-unauthenticated',
        '--set-env-vars', 'NEXT_PUBLIC_SUPABASE_URL=${_NEXT_PUBLIC_SUPABASE_URL},NEXT_PUBLIC_SUPABASE_ANON_KEY=${_NEXT_PUBLIC_SUPABASE_ANON_KEY}'
      ]

substitutions:
  _NEXT_PUBLIC_SUPABASE_URL: "https://ysumzdpydvotjqkkczbz.supabase.co"
  _NEXT_PUBLIC_SUPABASE_ANON_KEY: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlzdW16ZHB5ZHZvdGpxa2tjemJ6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ0MjEzODMsImV4cCI6MjA1OTk5NzM4M30.4d5WzQg7blJ-4Yy5nF3cwMw76vq1pVQLvYeUmGgbgis"
